---
name: DDNS-GO
version: v6.6.5
slug: ddns-go
description: 简单好用的DDNS。DDNS-GO自动获得你的公网 IPv4 或 IPv6 地址，并解析到对应的域名服务。支持的域名服务商：阿里云、腾讯云Dnspod、cloudflare、华 云、百度云、Porkbun、GoDaddy、Google Domains以及自定义Callback。
url: https://github.com/dscao/hassio-addons/tree/master/ddns-go
image: dscao/{arch}-addon-ddns-go
advanced: true
arch:
  - aarch64
  - amd64
hassio_api: true
hassio_role: manager
host_network: true
init: false
map:
  - config:rw
webui: "[PROTO:ssl]://[HOST]:[PORT:9876]"
panel_icon: mdi:dns
panel_title: ddns-go
ports:
  9876/tcp: 9876
ports_description:
  9876/tcp: Web interface
options: 
  ddnsgo_time_seconds: 300
schema:
  ddnsgo_time_seconds: "int(60,)"
startup: services
