---
name: tiles-gaode
version: 1.0
slug: tiles-gaode
description: 高德地图纠偏版 for Traccar
url: https://github.com/dscao/hassio-addons/tree/master/tiles-gaode
image: dscao/{arch}-addon-tiles-gaode
arch:
  - aarch64
  - amd64
init: false
ports:
  8080/tcp: 8280
ports_description:
  8080/tcp: "web interface"
startup: services
